spring.application.name=IKO-Myanmar-Karate-Schools-Backend

# spring.datasource.url=jdbc:mysql://localhost:3306/iko_myanmar
# spring.datasource.username=root
# spring.datasource.password=53545556

spring.datasource.url=jdbc:mysql://mysql-3c4515e8-iko-myanmar-karate-schools-database.h.aivencloud.com:20914/iko_myanmar
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_5fb2__qijRjvLE0_CEZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# swagger-ui custom path
springdoc.swagger-ui.path=/iko-myanmar-karate-schools-backend/swagger-ui.html