spring.application.name=IKO-Myanmar-Website

spring.datasource.url=jdbc:mysql://localhost:3306/iko_myanmar
spring.datasource.username=root
spring.datasource.password=53545556

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true