spring.application.name=IKO-Myanmar-Karate-Schools-Backend

spring.datasource.url=jdbc:mysql://localhost:3306/iko_myanmar
spring.datasource.username=root
spring.datasource.password=53545556

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# swagger-ui custom path
springdoc.swagger-ui.path=/iko-myanmar-karate-schools-backend/swagger-ui.html